### ISSUE TITLE
Unable to set `ip-address` to `"Private"`

### ISSUE THREAD

**Issue by mtbdeano** [Azure/aci-deploy#40] opened 2021-02-23 20:44 UTC
Same error as https://github.com/Azure/aci-deploy/issues/17

https://github.com/Azure/aci-deploy/blob/10a287e023e486030363702cbfbca3ffd0b793ee/src/taskparameters.ts#L71

The above is obvs a bug the and condition is incorrect and makes it so that you are unable to set the ip address to Private because this is always only true for Public. 

As a workaround, I'll have to stop using this ACI and manually create github action command line deploys using `az container create`

**Comment by kanika1894** [comment] 2021-04-15 09:59
Closing as it is duplicate of https://github.com/Azure/aci-deploy/issues/3

**Closed by kanika1894** 2021-04-15 09:59 UTC
