### ISSUE TITLE
Prophet Model Deployment ERROR

### ISSUE THREAD

**Issue by NumtraAdmin** [Azure/aci-deploy#68] opened 2021-12-23 11:57 UTC
**Description:**
I am trying to deploy Prophet Model.
Model is logged as mlflow.prophet flavour.
When I am creating image from Model Artifact this error came :
WebserviceException: WebserviceException:
"error": {
"message": "Image creation polling reached non-successful terminal state, current state: Failed\nError response from server:\nStatusCode: 400\nMessage: Docker image build failed."
}
}

**Code to reproduce issue**
```
import azureml
import mlflow.azureml
from azureml.core import Workspace
from azureml.core.authentication import ServicePrincipalAuthentication
from azureml.core.webservice import AciWebservice, Webservice

principal_auth = ServicePrincipalAuthentication(tenant_id, principal_id, app_secret)
workspace = Workspace.get(name=workspace_name, subscription_id=subscription_id, auth=principal_auth, resource_group=workspace_rg)
model_image, azureml_model = mlflow.azureml.build_image(model_uri='runs:/016fc3f2d5c34c8eadbeb20ad16d3/082358timeseriesforecasting', workspace=workspace)
model_image.wait_for_creation(show_output=True)
```

**Other info / logs**

**In Container logs error is shown below:**

[0mThe command '/bin/sh -c CONDA_ROOT_DIR=$(conda info --root) && if [ -n "$AZUREML_CONDA_ENVIRONMENT_PATH" ]; then conda env update -p "$AZUREML_CONDA_ENVIRONMENT_PATH" -f '/var/azureml-app/conda.yaml'; else conda env update -n base -f '/var/azureml-app/conda.yaml'; fi && conda clean -aqy && rm -rf /root/.cache/pip && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name pycache -exec rm -rf {} +' returned a non-zero code: 137
2021/11/23 12:21:39 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 137

Run ID: cj58 failed after 6m19s. Error: failed during run, err: exit status 1

**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Azure Distributed cluster
MLflow installed from (source or binary): source
MLflow version (run mlflow --version): 1.12.0
Python version: 3.7.3

**Comment by BALAGA-GAYATRI** [comment] 2021-12-30 09:04
@NumtraAdmin This repository's issues forum deals with `azure/aci-deploy` github action only. If you are using this action inside github workflow and facing this issue please do share your workflow here.

**Comment by AjayKaleMS** [comment] 2022-01-25 06:48
Hi @NumtraAdmin - Assuming the issue is not with the action, we are closing this issue. 
Please feel free to reopen the issue in case you have anything related to this particular action.

Thanks.

**Closed as completed** 2022-01-25 06:50 UTC
Labels: question, idle
